# Generated by Django 3.2.13 on 2022-11-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtusig_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envelop_display',
            options={'managed': True},
        ),
    ]
