# Generated by Django 3.2.13 on 2022-11-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtusig_app', '0002_alter_envelop_display_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envelop_display',
            options={'managed': False},
        ),
    ]
