# Generated by Django 3.2.13 on 2022-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusig_app', '0003_alter_envelop_display_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_password', models.CharField(blank=True, max_length=255, null=True)),
                ('recepient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('cc', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'envelop_display',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('email_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'login_user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Envelop_Display',
        ),
        migrations.DeleteModel(
            name='VirtusigAppLoginuser',
        ),
    ]
