# Generated by Django 3.2.13 on 2022-11-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusig_app', '0004_auto_20221117_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgot_password_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forgot_password',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
